export const theme = {
  _name: 'aragon-migrate',
  _appearance: 'light',
  accent: '#00c2ff',
  accentStart: '#01e8f7',
  accentEnd: '#00c2ff',
  disabledContent: '#a0a8c2',
  positive: '#38ccb6',
  positiveSurface: '#ecfaf8',
  negative: '#ff7163',
  contentSecondary: '#9ca3bd',
  surfaceContentSecondary: '#757d9c',
  surfaceSelected: '#fdfefe',
  tagIdentifier: '#6f7ca6',
}
